### ISSUE TITLE
Typo in repo description

### ISSUE THREAD

**Issue by karlhorky** [stereobooster/lqip.macro#3]
Hi there, thanks for this project! 

Just a small typo in the repo description:

<img width="220" alt="Screen Shot 2019-10-10 at 10 52 44" src="https://user-images.githubusercontent.com/1935696/66553984-653c4000-eb4c-11e9-8149-2249a7613c2e.png">

```diff
- Cretes
+ Creates
```

**Comment by stereobooster** [comment]
FIxed, thanks!
